name: python 3.6
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - control
  - sympy
  - lxml
  - xlrd
  - networkx
  - csv
  - pip
  - pip:
    - svgpathtools
    - datetime
    - cobra
    - BondGraphTools

